MD013: # allow long line length in code blocks and tables
  code_blocks: false
  tables: false
MD026: false # allow trailing punctuation
MD033: false # allow inline HTML
MD041: false # allow non-headers as first lines
