name: Build Docs

on:
  # trigger this workflow every time a branch is pushed
  push:
  # enable running this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# allow this job to clone the repo
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build
