name: Build Docs

on:
  # Trigger this workflow every time a branch is pushed.
  push:
  # Enable running this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      # - name: Install Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        # with:
        #   package-manager: bun # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
